{% set name = "tango-admin" %}
{% set version = "1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/tango_admin/-/archive/Release_{{ version }}/tango_admin-Release_{{ version }}.tar.gz
  sha256: 6af2a607bda0b7694d328e013398a87bf3d7b94a1db4fbb0946144277e62445a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb
    - omniorb-libs

test:
  commands:
    - tango_admin --help

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango database command line interface
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This utility is a Tango database command line interface.
    Obviously, not all the database features are interfaced by this tool.
  dev_url: https://gitlab.com/tango-controls/tango_admin

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
