{% set name = "tango-admin" %}
{% set version = "1.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/tango_admin/-/archive/Release_{{ version }}/tango_admin-Release_{{ version }}.tar.gz
  sha256: 9cd36a240b4d966ebb3334088d7433e17f82502edb0d1a0dd5900a9ba94f2a40

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb

test:
  commands:
    - tango_admin --help

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango database command line interface
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This utility is a Tango database command line interface.
    Obviously, not all the database features are interfaced by this tool.
  dev_url: https://gitlab.com/tango-controls/tango_admin

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
